### ISSUE TITLE
 apiRequest Endpoint URL is wrong for search videos. 

### ISSUE THREAD

**Issue by prakuda** [clickntap/Vimeo#15]
In Vimeo Class  
`public VimeoResponse searchVideos(String query) throws IOException {
        return apiRequest("/me/videos?query=" + query, HttpGet.METHOD_NAME, null, null);
    }`

**"/me/videos?query=" + query, HttpGet.METHOD_NAME**" -> is wrong URL 

it should be "**/videos?query=" + query, HttpGet.METHOD_NAME**"

**/me** is not required.

**Comment by morisbartyno** [comment]
[/d](url)

**Comment by morisbartyno** [comment]
![screenshot_2016-08-11-21-02-01](https://cloud.githubusercontent.com/assets/14913140/17643447/08929f34-6184-11e6-8473-05397b432fa8.png)
